//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExamApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int Id { get; set; }
        public string CityAddress { get; set; }
        public string StreetAddress { get; set; }
        public string HouseAddress { get; set; }
        public string ApartmentNumberAddress { get; set; }
        public Nullable<double> CoordinateLatitude { get; set; }
        public Nullable<double> CoordinateLongitude { get; set; }
        public Nullable<int> TotalFloors { get; set; }
        public Nullable<double> TotalArea { get; set; }
    }
}
