//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExamApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> RealtorId { get; set; }
        public Nullable<int> RealEstateId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual RealEstate RealEstate { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
